version: '3.8'

services:
  weather-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-service
    ports:
      - "8080:8080"
    environment:
      - CONFIG_FILE=config.json
      - PORT=8080
      - UPDATE_INTERVAL=5m
      - ENABLE_RATE_LIMIT=true
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - WEATHERAPI_KEY=${WEATHERAPI_KEY}
    volumes:
      # Mount custom config if needed
      - ./config.json:/app/config.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/api/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s 